import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useCustomerInfoStore = defineStore('customInfo', {
  state: () => ({
    info: ref({}),
  }),
  actions: {
    updateCustomerInfo(list: any) {
      this.info.value = list;
    },
  },
});

export const useRecommendStore = defineStore('recommends', {
  state: () => ({
    recommends: ref([]),
  }),
  actions: {
    getRecommends() {
      const recommends = ref([
        {
          id: '514d10b6-6a4d-4541-a8c7-7eba3340a175',
          uid: '5b74e930-e427-4eba-aa6c-877c45d3b482',
          customer_group: [],
          name: '裴裴',
          avatar: 'https://static.hamu.site/blind/e925309c051c4ecca643d43a725a3990/1721381430258.png',
          is_only: [],
          operate_id: '100000',
          operate_type: '微信小程序-核心资料',
          cover_img: 'https://static.hamu.site/blind/e925309c051c4ecca643d43a725a3990/1721381430258.png',
          img_list: [
            'https://static.hamu.site/blind/c9429a1c19ed438d8583ce964b923c6d/1721381457021.png',
            'https://static.hamu.site/blind/d93193ade93d430ead7193bdd650aa23/1721381506050.png',
            'https://static.hamu.site/blind/3483b044d35b4572816a9e864cb5575c/1721381592936.png',
          ],
          image_list: [
            { type: 'travel', image: '' },
            { type: 'favorite', image: '' },
            { type: 'more', image: '' },
          ],
          gender: '女',
          birthday: 1003766400000,
          living_place: ['浙江省', '杭州市'],
          hometown: ['湖北省', '黄冈市'],
          register_residence: ['湖北省', '武汉市'],
          education: '本科',
          school: '四川师范大学',
          work_unit: '未知',
          assets: '50万内',
          position: ['学生', '大学生'],
          introduce: [
            'hi，你好，很高兴认识你，\n我是「裴裴」\n🏷湖北黄冈人，01年\n🎓本科毕业于四川师范大学，\n📌目前坐标天津，现在是在实习，未来计划是考研\n\n✨ 关于性格：\n天秤座女生一枚，\n我是个温柔有趣，娇小可爱的南方姑娘，\n性格开朗乐观，像只温柔的小兔子🐰，\n奶凶奶凶的时候，吃个草莓🍓就好啦。\n\n🧊 长相：\n身高170cm，\n长相比较温柔\n\n💻 工作：\n目前正在实习中，共事的都是女生\n同时也兼职',
          ],
          friends_impression: [],
          questions_answers: [{ A: '', Q: '' }],
          age: 22,
          height: 170,
          city: '天津市',
          university: '四川师范大学',
          ideal_object: {
            理想对象介绍:
              '坐标要求:   天津\n学历要求:   本科\n年龄范围:   18-35岁\n是否有房:   否\n收入要求:   5万\n身高要求:   168cm\n善良专一，理工科、会计算机加分  \n',
          },
          ideal_object_tags: [],
          remark: '',
          tags: [],
          common_tags: ['年入20万', '170cm'],
          admin_set_tags: [],
          sea_operator_id: '001-0186dde37d6d66d1',
          platform: 'mini',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 181,
          score: 5274,
          status: '审核通过',
          update_count: 26,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1675785600000,
          update_date: 1721447466069,
          is_buy: false,
          private_info: {
            年收入: '20',
            微信号: '申请通过后，可解锁',
            家庭背景: '非独生女，父母身体健康，母亲是一名英语教师，父亲在公办学校当语文教师，家庭和睦。',
            是否购房: '否',
            是否购车: '否',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_6.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '09002886-8511-4571-9904-d167d6893d0a',
          uid: '924e1784-1009-439e-924b-8c0c9b5670a6',
          customer_group: [],
          name: '02',
          avatar: 'https://static.hamu.site/blind/3de87459154d4a84bbeaa4b96a18435c/1671699571979.png',
          is_only: [],
          operate_id: '395453',
          operate_type: '嘉宾用户绑定',
          cover_img: 'https://static.hamu.site/blind/3de87459154d4a84bbeaa4b96a18435c/1671699571979.png',
          img_list: [
            'https://static.hamu.site/blind/d9c45dd9065140c49ea6972e7e24bd66/1671699594700.png',
            'https://static.hamu.site/blind/b791e408444747a0804094a2b8484534/1671699614696.png',
            'https://static.hamu.site/blind/6132ab4c918849cd9e268671bd33e7aa/1671699656487.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 855504000000,
          living_place: ['浙江省', '杭州市'],
          hometown: ['新疆维吾尔自治区', '克拉玛依市'],
          register_residence: [],
          education: '硕士',
          school: '西班牙巴塞罗那自治大学',
          position: ['公务员', '国企'],
          introduce: [
            'hi，你好，很高兴认识你，\n我是「02^」,\n🏷新疆人，97年，身高168，\n🎓本科在重庆，由于疫情原因求学之路gap了两年，\n🇪🇸21年录取到巴塞罗那自治大学读对外西语专业\n\n📌目前已经回国，定居杭州工作生活\n💻本科毕业后在杭州工作生活了一段时间，\n在父母的帮助下已在杭州买🏡\n\n♒可盐可甜\n本人脾气比较好～\n情绪稳定，会考虑对方的感受，\n喜欢撒娇，不作也不喜欢吵架。\n\n💕温和细心爱撒娇，\n爽快直接不矫情，\n​是一个很好相处的人。\n\n兴趣爱好：\n🍣热爱美食，对吃有要求，并且喜欢尝试和挑战。\n希望以后你能陪我去尝试更多美食。\n我几乎不挑食，但是不喜欢吃菜，\n尤其讨厌清炒油麦菜🥬。\n\n🏃🏻‍♀️正常一周会有3-4次的健身，\n针对塑形和腰臀比的训练🏋\n（当然还有小肚腩…主要做些力量训练、跳绳和游泳🏊‍♀️）。\n\n🍰喜欢探店\n经常和闺蜜去探店拍照，\n但目前还是不太愿意和男生去拍照，\n毕竟男生确实没有女生拍照好看😗\n\n✈️喜欢旅游\n在国内的时候，经常一个人会来一场说走就走的旅行。\n一般我习惯提前做好几天的计划、一天内的安排，\n并执行下去，不喜欢漫无目的的游玩。\n\n🔍也喜欢玩剧本杀狼人杀\n因为有潮人恐惧症，还没去过大型演唱会和音乐节。\n🏂🏻因为在新疆长大，特别喜欢滑雪，基本每年都要滑几次。\n\n📚平时大多数情况，\n我会在家宅着看看书、收拾房间，\n也会弹弹钢琴🎹（小时候只考了7级，现在基本只会识谱啦…），\n或者玩儿lol大乱斗和云顶下下棋。',
          ],
          friends_impression: [],
          questions_answers: [{ A: '', Q: '' }],
          age: 27,
          height: 168,
          city: '杭州市',
          university: '西班牙巴塞罗那自治大学',
          ideal_object: {
            理想对象介绍:
              '1. 我不是颜控。外表我没有太多要求，比我高、讲卫生就好，其他颜值方面都是锦上添花；\n\n2. 希望你年纪比我大一些，我觉得男生最重要的还是要有能力、有责任心，要成熟、情绪稳定。在一些大是大非上有自己的判断和决断；\n\n3.希望你有上进心、有一定的经济基础。也希望我们三观一致。\n',
          },
          ideal_object_tags: [],
          tags: [],
          common_tags: ['有房', '168cm', '硕士', '公务员'],
          admin_set_tags: [],
          is_on_wall: true,
          is_real_name_auth: false,
          is_show: true,
          is_ban: false,
          sort: 122,
          score: 4383,
          status: '审核通过',
          update_count: 1,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: false,
          create_date: 1671552000000,
          update_date: 1711001591346,
          is_buy: false,
          private_info: {
            微信号: '申请通过后，可解锁',
            家庭背景: '独生女，父母都是体制内，目前在新疆还没退休，没有养老压力。\n\n',
            是否购房: '是',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_8.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '34ece53c-38b9-4c09-8b2e-2631e9459458',
          uid: '34849913-d213-4c46-9b5c-8a97d32e8c9e',
          customer_group: [],
          name: 'Lucy',
          avatar: 'https://static.hamu.site/blind/91798370ae854455bda7d39494e475de.png',
          is_only: [],
          only_content: '',
          operate_id: '100001',
          operate_type: '微信小程序',
          cover_img: 'https://static.hamu.site/blind/91798370ae854455bda7d39494e475de.png',
          img_list: [
            'https://static.hamu.site/blind/42a824858a504db08c093dd8737dc0e7.png',
            'https://static.hamu.site/blind/b3e701ecebee41429ca080702674d2d7/1684310593255.png',
            'https://static.hamu.site/blind/1570552449664344841449c17e529352.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 826934400000,
          living_place: ['上海市'],
          hometown: ['上海市'],
          register_residence: ['上海市'],
          education: '本科',
          school: '上海师范大学',
          work_unit: '浦东小学',
          assets: '50万',
          job: '',
          position: ['老师', '小学老师'],
          introduce: [
            '嗨～你好呀，我是Lucy，\n🐣上海本地人，\n👩🏻‍🎓本科毕业于上海师范大学；\n📌是一名小学老师，家里有几套🏠和商铺，父母均稳定职业，感情和谐。\n\n♓️三观比五官正  自律\n性格温和，积极阳光；\n\n🌻爱笑，玩的时候比较活泼；\n平时喜欢和朋友旅行，滑雪，看音乐剧，\n喜欢轻松有趣的氛围（脾气好的人很棒）。\n\n人生经历：\n从小生活在上海，家里人给了我满满的爱',
          ],
          friends_impression: [
            '一个温柔又勇敢的有趣灵魂。她很温柔很热情，聪明又努力，相处起来也特别善解人意，在我眼里是完美的朋友啦，如果能和她携手共度之后的人生，我想一定会非常幸福。',
          ],
          questions_answers: [{ A: '', Q: '' }],
          age: 27,
          height: 163,
          city: '上海市',
          university: '上海师范大学',
          ideal_object: {
            理想对象介绍:
              '1. 希望你定居上海，年龄在30岁以下，身高175+；\n\n2. 希望你学历本科及以上，有稳定工作，收入稳定，无不良嗜好；\n\n3. 希望你和我有相似的兴趣爱好，身材匀称爱运动。',
          },
          ideal_object_tags: [],
          remark: '',
          tags: ['积极乐观', '旅游爱好者', '羽毛球', '台球', '滑雪'],
          common_tags: ['有房', '沪户', '年入20万', '老师'],
          admin_set_tags: [],
          sea_operator_id: '350381',
          sea_type: '前一天注册',
          sea_status: 'D',
          sea_current_id: '5d25c14e-4706-44d6-a7a0-d1bd42b1a96a',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 100,
          score: 4343,
          status: '审核通过',
          update_count: 6,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1662912000000,
          update_date: 1720833261904,
          is_buy: false,
          private_info: {
            年收入: '20',
            微信号: '申请通过后，可解锁',
            家庭背景:
              '独生女，普通家庭，父母普通员工，工作稳定，身体健康，感情和谐，有几套拆迁房。爸爸妈妈开明有趣，从小给了我良好的教育，尊重我的意见，支持我的选择，在我迷茫和遇到困难时会给出建议，所以空闲时间也会多陪陪他们。',
            是否购房: '是',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_8.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: 'cb14c58a-7184-414d-b1ac-6b745c5a1712',
          uid: '32b95055-d720-4915-a3ea-39002807a4ed',
          customer_group: [],
          name: 'Dva👑沐沐',
          avatar: 'https://static.hamu.site/blind/0676d2380a994489b796c95b30ca0095/1697790739200.png',
          is_only: [],
          only_content: '',
          operate_id: '100000',
          operate_type: '微信小程序-核心资料',
          cover_img: 'https://static.hamu.site/blind/0676d2380a994489b796c95b30ca0095/1697790739200.png',
          img_list: [
            'https://static.hamu.site/blind/0ec95346454943adac909de4beb93561/1686899784023.png',
            'https://static.hamu.site/blind/9c32154ba4174221b460bc76e73d8834/1686899803944.png',
            'https://static.hamu.site/blind/90c2074a3de349559bb491090701bd41/1697790759191.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 828662400000,
          living_place: ['广东省', '深圳市'],
          hometown: ['江苏省', '扬州市'],
          register_residence: ['广东省', '广州市'],
          education: '硕士',
          school: '香港城市大学',
          work_unit: '网易游戏',
          assets: '1亿+',
          job: '',
          position: ['市场', '市场/营销'],
          introduce: [
            '关于我：\n\n📌广州深圳都可以，目前在广州\n\n如有缘分请直接申请，不查看喜欢\n\n\n\n🎈个人履历：\n\n*华映签约平面模特\n\n*理工科一等学位(伪)学霸\n\n*互联网游戏大厂赛事策划\n\n*搞了点小副业赚个胭脂钱\n\n*国家二级马术(盛装舞步)运动员\n\n🙅不是主播，不是外包，同年龄段职级最高的策划之一，不接受漂亮女生没大脑的论调。',
          ],
          friends_impression: [],
          questions_answers: [],
          age: 28,
          height: 168,
          city: '深圳市',
          university: '香港城市大学',
          ideal_object: {
            理想对象介绍:
              '1. 男生如果不能主动，那就默认没缘分👋🏻；男生如果不付出，或斤斤计较一秒下头👋🏻；\n\n2. 有小才华的小哥爆灯（不论是有一份很好的事业，有自己的小爱好，或者有独特的阅历和见解都很棒呐！）\n\n3. 最好是有留学或者香港读书的经历，我两个能谈到一起去；\n\n4. 有责任感有担当就更好啦！毕竟我讨厌妈宝和巨婴，没能力减分（我们白羊座就是喜欢很强大的男孩子！',
          },
          ideal_object_tags: [],
          remark: '',
          tags: [
            '积极乐观',
            '容易相处',
            '传统的',
            '有氧运动',
            '看书',
            '剧本杀',
            '狼人杀',
            '密室逃脱',
            '寻觅美食',
            '游乐场',
            '做饭',
            '逛博物馆',
            '跑步',
            '游泳',
            '射击',
            '瑜伽',
            '滑雪',
            '冲浪',
            '跆拳道',
            '潜水',
          ],
          common_tags: ['有房', '年入50万', '168cm', '硕士', 'QS48'],
          admin_set_tags: ['QS48'],
          sea_operator_id: '6d5c32dc-e57a-4038-aca0-0dad13ac1965',
          sea_type: '社群',
          sea_status: 'B',
          sea_current_id: 'c7241679-b1a5-42cc-a4e4-7e40cea0d683',
          platform: 'mini',
          is_on_wall: true,
          is_real_name_auth: false,
          is_show: true,
          is_ban: false,
          sort: 103,
          score: 4227,
          status: '审核通过',
          update_count: 5,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1686758400000,
          update_date: 1720684199541,
          is_buy: false,
          private_info: {
            年收入: '50',
            微信号: '申请通过后，可解锁',
            家庭背景:
              '公务员父母，一位是国家工程师，一位是电气工程师。父母是同学，非常恩爱开明，经常在我面前撒狗粮。家庭氛围极好，独生。\n\n\n\n受到爸爸妈妈的影响也一直非常渴望有一个温馨幸福的小家，一段像父母般的爱情/亲情。我很喜欢小宠物，小宝宝，希望未来有我们自己的呢~',
            是否购房: '是',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_2.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '56cecb1d-d8e0-41a4-a154-1164a10918de',
          uid: '35b88604-4526-4a5a-8bbb-ee4c70e7d6c6',
          customer_group: [],
          name: 'Jessie',
          avatar: 'https://static.hamu.site/blind/a2cc6b1bb10845d889884c342601d13a/1680847844578.png',
          is_only: [],
          operate_id: '395453',
          operate_type: '嘉宾用户绑定',
          cover_img: 'https://static.hamu.site/blind/a2cc6b1bb10845d889884c342601d13a/1680847844578.png',
          img_list: [
            'https://static.hamu.site/blind/56c815179ce64e0cb06b7b274c1b1646/1680847937653.png',
            'https://static.hamu.site/blind/63ee021c538641d38bd98042b00e97a9/1680847952839.png',
            'https://static.hamu.site/blind/6a30ce49e3c049c98a59ed8e9934b941/1697622644590.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 901814400000,
          living_place: ['上海市'],
          hometown: ['上海市'],
          register_residence: ['上海市'],
          education: '本科',
          school: '上海师范大学',
          work_unit: '市示范幼儿园',
          assets: '1000万',
          position: ['老师', '幼教'],
          introduce: [
            'hi，你好，很高兴认识你，\n我是「Jessie」👧🏻\n🏷98年，上海人，身高170\n🎓本科毕业于上海师范大学\n📌现在坐标上海，是黄浦区公办幼儿园的一名老师\n👩🏻‍🏫编制里的生活导致圈子比较小，认识不到异性😅所以就来这里试试看啦~\n\n✨ 关于性格：\n自己性格比较直爽\n会明确表达自己的想法和需求\n共情能力强，情绪稳定🍀\n出生在七月的尾巴，\n是一个温暖、勇敢的狮子座女孩👧\n\n🍀内心有自己的小坚持\n有时也会像小孩子一样，直率、热情、冲动。\n在对待自己想要完成的事情上，会非常认真，\n是一个有始有终，不会半途而废的人！\n\n人生经历：\n✈️大学时期去过日本、澳洲做交换生，体验了不同的教育文化，对年少的我来说感触很深。世界多元，每个人都是独立有趣的个体，希望求同存异呀✌🏻\n\n兴趣爱好：\n✈️喜欢旅行，\n周末假期喜欢躺平游😹\n喜欢泡泡酒店\n\n🍲休息时间喜欢和家里人聚聚餐，\n也喜欢和小姐妹一起探店打卡📷\n\n喜欢小朋友😺\n想有自己的小朋友，超级爱娃\n当然有小朋友的前提是有个喜欢的男孩😝',
          ],
          friends_impression: [],
          questions_answers: [{ A: '', Q: '' }],
          age: 25,
          height: 170,
          city: '上海市',
          university: '上海师范大学',
          ideal_object: {
            理想对象介绍:
              '1. 希望你坐标上海，性格好，不逃避问题，遇到矛盾愿意沟通；\n2. 希望你情绪稳定，是有话直说的类型，两个人共同调整，相信会一起走向美好的未来💕\n',
          },
          ideal_object_tags: ['非常自律', '做事严谨', '性格沉稳', '理性待事'],
          remark: '',
          tags: [
            '比较主动',
            '积极乐观',
            '容易相处',
            '王者荣耀',
            '密室逃脱',
            '寻觅美食',
            '游泳',
            '跳舞',
            '潜水',
            '滑雪',
          ],
          common_tags: ['有房', '沪户', '年入20万', '170cm', '老师'],
          admin_set_tags: [],
          sea_operator_id: '350381',
          sea_type:
            '前一天喜欢嘉宾:http://mp-admin.smcode.com.cn/operator/user_detail?id=6b820471-c599-4d88-a34a-823a087d6067&name=徐晓&type=0&source=all',
          sea_status: 'D',
          sea_current_id: 'baa573bc-9763-4293-8b94-9147bcbd6370',
          is_on_wall: true,
          is_real_name_auth: false,
          is_show: true,
          is_ban: false,
          sort: 107,
          score: 4178,
          status: '审核通过',
          update_count: 11,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1680710400000,
          update_date: 1720620602239,
          is_buy: false,
          private_info: {
            年收入: '20',
            微信号: '申请通过后，可解锁',
            家庭背景:
              '上海人，父母工薪阶层，家庭和睦。父母非常理解和尊重我，也经常能给我很多的启发和勇气，是我学习的榜样。\n',
            是否购房: '是',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_6.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '73687b47-e28c-4c44-9890-b0a8de53d7d1',
          uid: '9a6b34c7-3046-46ba-a970-5ea47b905210',
          customer_group: [],
          name: '张雨薇',
          avatar: 'https://static.hamu.site/blind/8c99d21d5d2c431ab0e29868e0a2c636/1663926844101.png',
          is_only: [],
          only_content: '',
          operate_id: '100000',
          operate_type: '微信小程序',
          cover_img: 'https://static.hamu.site/blind/8c99d21d5d2c431ab0e29868e0a2c636/1663926844101.png',
          img_list: [
            'https://static.hamu.site/blind/c23da80a87b9440e8b1784a66ee00c70/1663912980787.png',
            'https://static.hamu.site/blind/d1b061e4877a42819c3b59535a1dab1c/1663926864605.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 915321600000,
          living_place: ['北京市'],
          hometown: ['辽宁省', '沈阳市'],
          register_residence: [],
          education: '硕士',
          school: '北京师范大学',
          work_unit: '。',
          assets: '50万内',
          job: '',
          position: ['老师', '初中老师'],
          introduce: [
            '💕 映夏向你报道~\n🙆🏻‍♀️ 来自辽宁省沈阳市\n📚 北京师范大学\n\n👩🏻‍🏫 中学美术老师\n🏡🚗 家里有，本人木有呀\n\n🌙 一个爱笑的月牙眼女孩⌒ ▽ ⌒\n\n🏷 反差萌\n有好静的一面，也有乐群的一面\n待人温柔随和，做事严肃认真\n通常沉着稳重，时而异想天开\n既有浪漫幻想，又有理性思考\n\n☁️ 非典型性格\n有INFJ的温柔沉静\n也有摩羯座的爱规划\n还有上升水瓶的天马行空\n\n👻 不过，我写归我写嘛~每个人都是很繁杂的个体啦！\n希望可以通过我们的相处，慢慢了解\n了解这个鲜活多样的我~\n\n兴趣爱好：\n🏃🏻‍♀️ 运动\n喜欢🏊‍♀️游泳、🧘瑜伽、🤸‍♀️跳操\n偶尔🏸羽毛球、🏓乒乓球\n🤼还有点子合气道在身上\n水平都一般，属于人菜又爱玩哈哈哈~\n\n😋 外出\n通常会看看展览什么的~\n或者跟好姐妹一起吃饭逛街玩耍~\n\n🖼 宅家\n不出门的话，会画画、看书\n或者看看剧~\n\n✨ 期待发掘一些新的共同爱好！',
          ],
          friends_impression: [],
          questions_answers: [],
          age: 25,
          height: 163,
          city: '北京市',
          university: '北京师范大学',
          ideal_object: {
            理想对象介绍:
              '1. 希望你坐标北京，身高175+，学历本科及以上；\n2. 希望你三观正，温柔善良，情绪稳定；\n3. 希望你无不良嗜好，遇事愿意沟通；\n4. 加分项：年龄在28岁以下，喜欢干净整洁，笑容灿烂的人～',
          },
          ideal_object_tags: [
            '积极乐观',
            '正直',
            '容易相处',
            '有点小幽默',
            '比较主动',
            '有氧运动',
            '看书',
            '逛博物馆',
            '做饭',
            '手绘',
            '跑步',
            '羽毛球',
            '乒乓球',
            '听音乐',
            '寻觅美食',
            '游泳',
            '慢走',
          ],
          remark: '',
          tags: [
            '喜欢安静',
            '倾听者',
            '容易相处',
            '性格沉稳',
            '看书',
            '拍照片',
            '逛博物馆',
            '有氧运动',
            '跑步',
            '游泳',
            '瑜伽',
            '慢走',
            '羽毛球',
            '乒乓球',
            '寻觅美食',
            '手绘',
          ],
          common_tags: ['硕士', '老师', '师范院校'],
          admin_set_tags: ['师范院校'],
          sea_operator_id: '',
          sea_type: '',
          sea_status: '',
          sea_current_id: '',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 85,
          score: 3912,
          status: '审核通过',
          update_count: 5,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: false,
          create_date: 1663603200000,
          update_date: 1724985130121,
          is_buy: false,
          private_info: {
            年收入: 10,
            微信号: '申请通过后，可解锁',
            家庭背景:
              '独生女，母亲老师，父亲企业经理。家里很多老师~\n教育方面，从严格到逐渐放养，小学时候还会辅导我，后来就自己学了，职业发展会给些建议和指导。\n成长环境是吵闹+欢笑。家人们都很亲切，相处融洽，对我很好！',
            是否购房: '否',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_1.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '4dd044b5-41d8-4121-a499-35423c68cc06',
          uid: 'e3d0437e-040e-4bbc-84c4-544115be4923',
          customer_group: [],
          name: '阿如娜',
          avatar: 'https://static.hamu.site/blind/7a14d9a06e2543ce822c8e9779706610.png',
          is_only: [],
          only_content: '',
          operate_id: '161089',
          operate_type: '微信小程序-核心资料',
          cover_img: 'https://static.hamu.site/blind/7a14d9a06e2543ce822c8e9779706610.png',
          img_list: [],
          image_list: [],
          gender: '女',
          birthday: 744940800000,
          living_place: ['内蒙古自治区', '呼和浩特市'],
          hometown: ['内蒙古自治区', '呼和浩特市'],
          register_residence: [],
          education: '硕士',
          school: '',
          job: '',
          position: ['公务员', '公务员'],
          introduce: ['简单纯粹，爱是疲惫生活中的英雄梦想！独立善良上进，愿我们的相遇会成就更好的自己！'],
          friends_impression: [],
          questions_answers: [
            { A: '', Q: '' },
            { A: '', Q: '' },
            { A: '', Q: '' },
          ],
          age: 29,
          height: 168,
          city: '呼和浩特市',
          university: '',
          ideal_object: { 理想对象介绍: '稳重、善良、上进！不以自我为中心！不大男子主义！' },
          ideal_object_tags: [],
          remark: '',
          tags: [],
          common_tags: ['有房', '168cm', '硕士', '公务员'],
          admin_set_tags: [],
          sea_operator_id: '',
          sea_type: '',
          sea_status: '',
          sea_current_id: '',
          is_on_wall: true,
          is_real_name_auth: false,
          is_show: true,
          is_ban: false,
          sort: 1,
          score: 3644,
          status: '审核通过',
          update_count: 3,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 1672754780802,
          is_update_privacy: false,
          create_date: 1672754644455,
          update_date: 1672754954229,
          is_buy: false,
          private_info: { 年收入: '15', 微信号: '申请通过后，可解锁', 是否购房: '是' },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_10.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '76c421b6-5c45-4d52-abb1-94184c5c118c',
          uid: '8691d89a-0b96-4030-9103-0a700902dd16',
          customer_group: [],
          name: '麋鹿',
          avatar: 'https://static.hamu.site/blind/d72969e6387840d99c60711d21bb0029/1692431352860.png',
          is_only: [],
          only_content: '',
          operate_id: '100000',
          operate_type: '微信小程序-核心资料',
          cover_img: 'https://static.hamu.site/blind/d72969e6387840d99c60711d21bb0029/1692431352860.png',
          img_list: [
            'https://static.hamu.site/blind/ca8710941d054d17ba9946d6c91aa47a/1692431392445.png',
            'https://static.hamu.site/blind/024993790300493bb48a9830dbb55a99/1692431414636.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 837993600000,
          living_place: ['北京市'],
          hometown: ['河北省', '承德市'],
          register_residence: [],
          education: '本科',
          school: '河北地质大学',
          job: '',
          position: ['人事/财务/行政', '财务'],
          introduce: [
            '🦁 96年7月底出生\n🏙 北京本地人\n🏡 已购房\n\n💻 是一名中国注册会计师\n目前工作基本朝九晚五\n整体压力不大，也有更多的时间来提升自己\n\n🏷 关于性格\n可能看起来会有一点高冷\n但实际是个很温和的人\n对未来有自己的计划和规划\n也是一个很容易感到幸福的人~\n始终认为每天能够开心快乐就好啦！\n\n兴趣爱好：\n🎵 音乐\n音乐于我来说\n也是一味治愈性良药\n能够在不同的时候给予不一样的力量\n\n🏃🏻‍♀️ 运动\n有时也会出门运动一下\n\n📖 看书\n窝在家里的时候就会看看书\n享受当下的宁静\n和通过阅读带来的提升&新的感悟',
          ],
          friends_impression: [],
          questions_answers: [{ A: '', Q: '' }],
          age: 27,
          height: 165,
          city: '北京市',
          university: '河北地质大学',
          ideal_object: {
            理想对象介绍:
              '我心目中的你：接受过良好教育，有稳定工作和收入，事业心强，生活习惯健康，爱运动，长得好看，长得合眼缘，不抽烟不喝酒，为人善良，三观正，思想成熟，不幼稚。',
          },
          ideal_object_tags: [],
          remark: '',
          tags: [],
          common_tags: ['有房', '年入20万', '165cm'],
          admin_set_tags: [],
          sea_operator_id: '192185',
          sea_type: '前一天注册',
          sea_status: 'C',
          sea_current_id: '0a4079a1-34d4-49d2-a338-a03b73176c82',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 126,
          score: 3571,
          status: '审核通过',
          update_count: 14,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 1672995797831,
          is_update_privacy: true,
          create_date: 1672934400000,
          update_date: 1720143272861,
          is_buy: false,
          private_info: {
            年收入: '20',
            微信号: '申请通过后，可解锁',
            家庭背景: '独生女，父亲在国企就职，母亲任职于医院。三口小家，简单温馨。',
            是否购房: '是',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_5.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '2e78b475-7ec3-4e14-950b-73029dcaee89',
          uid: 'aad111a6-6aed-4e52-8d61-011ed2e297a1',
          customer_group: [],
          name: 'Ting',
          avatar: 'https://static.hamu.site/blind/ae47d566a2074bada76bb07b0b00cad0/1708161771011.png',
          is_only: [],
          operate_id: '987-018b9315c2c54937',
          operate_type: '嘉宾用户绑定',
          plan_id: '2023111101',
          cover_img: 'https://static.hamu.site/blind/ae47d566a2074bada76bb07b0b00cad0/1708161771011.png',
          img_list: [
            'https://static.hamu.site/blind/255755a66a9e4888b6c3b97053b33458/1673515672428.png',
            'https://static.hamu.site/blind/3122e0094b494e19843d00181837a732/1708155120993.png',
            'https://static.hamu.site/blind/288a230356344da18330150447230632/1708155134559.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 884448000000,
          living_place: ['上海市'],
          hometown: ['四川省'],
          register_residence: [],
          education: '专科',
          school: '西南财经大学',
          position: ['人事/财务/行政', '行政'],
          introduce: [
            'hi，你好，很高兴认识你，\n🐣四川人，98年，身高170\n📌现在坐标上海，在一家公司做行政工作。\n\n🏷关于性格：\n♑活泼大方\n脾气很好，大大咧咧乐天派一枚\n有的时候也会有一点犯傻，哈哈\n但只是稍微有一点啦。\n\n☁️可能因为外貌，\n很多人刚开始认识的时，\n会觉得我很高冷，\n其实熟了之后就会发现我的本性🤣。\n\n🍀作为一个典型摩羯座女生，\n虽然表面看上去大大咧咧，\n但其实内心非常敏感细腻。\n能够很快察觉到周围人的情绪，\n非常能够换位思考。\n\n🌊所以身边姐妹遇到事情的时候，\n都会告诉我，让我给她们做心理疏导。\n一不小心就成了大家的知心姐姐🐱\n\n兴趣爱好：\n\n🍰空闲时间，喜欢和朋友们一起去打卡探店；\n📷喜欢拍美美的照片\n🍲喜欢治愈的美食，喜欢街边的小花。\n🌈立志把美学主义践行到底。\n\n🏸运动方面比较喜欢打羽毛球，\n运动可以放松心情呀，\n而且对抗性运动还能和朋友一起，\n就更加开心啦✌🏻~',
          ],
          friends_impression: [],
          questions_answers: [{ A: '', Q: '' }],
          age: 26,
          height: 170,
          city: '上海市',
          university: '西南财经大学',
          ideal_object: {
            理想对象介绍:
              '1. 希望你年龄在24-35岁之间，身高170以上，学历不限，坐标上海；\n2. 希望你善良有担当，有责任感，为人正直；\n3. 有良好的思想价值观，成熟一点，学霸加分！\n\n\n',
          },
          ideal_object_tags: [],
          remark: '',
          tags: [],
          common_tags: ['170cm'],
          admin_set_tags: [],
          sea_operator_id: '',
          sea_type: '',
          sea_status: '',
          sea_current_id: '',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 125,
          score: 3530,
          status: '审核通过',
          update_count: 0,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1673452800000,
          update_date: 1720140185588,
          is_buy: false,
          private_info: {
            年收入: 15,
            微信号: '申请通过后，可解锁',
            家庭背景:
              '家庭氛围轻松和谐，独生女。父母很开明，会理解和尊重我的选择，不会过多地干涉，给我充分的自主选择权。虽然是独生女，但不会过分溺爱，父母之间一直很恩爱，从小在充满爱的环境中长大。',
            是否购房: '否',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_3.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '89000122-a4ae-4209-822a-52bcdced0c47',
          uid: '470b6228-311d-4953-9301-1639c928d2d8',
          customer_group: [],
          name: '徐绘婷',
          avatar: 'https://static.hamu.site/blind/41c4713392e747c48b12a879de966db9.png',
          is_only: [],
          only_content: '',
          operate_id: '987-018b8f91866f1738',
          operate_type: '微信小程序',
          plan_id: '240104',
          cover_img: 'https://static.hamu.site/blind/41c4713392e747c48b12a879de966db9.png',
          img_list: [
            'https://static.hamu.site/blind/d254121799e74503a6a06b8a4c46312e.png',
            'https://static.hamu.site/blind/1dcb64b428a947999b96791ccc76db6d.png',
            'https://static.hamu.site/blind/3291431457ce4057b14b48b1a8608a14.png',
          ],
          image_list: [
            { type: 'travel', image: 'https://static.hamu.site/blind/d254121799e74503a6a06b8a4c46312e.png' },
            { type: 'favorite', image: 'https://static.hamu.site/blind/1dcb64b428a947999b96791ccc76db6d.png' },
            { type: 'more', image: 'https://static.hamu.site/blind/3291431457ce4057b14b48b1a8608a14.png' },
          ],
          gender: '女',
          birthday: 925516800000,
          living_place: ['浙江省', '杭州市'],
          hometown: ['浙江省', '金华市'],
          register_residence: ['浙江省', '金华市'],
          education: '本科',
          school: '浙江传媒学院',
          work_unit: '天娱传媒',
          assets: '50万内',
          job: '',
          position: ['影视传媒', '模特'],
          introduce: [
            'hi 我现在在杭州从事平面模特，平时很爱笑，性格比较温柔文静，不抽烟不喝酒平时比较宅 爱健身滑雪滑板等运动 偶尔喜欢旅旅游 平时作息规律 生活简单 希望能遇到合得来的另一半一起平平淡淡的过我们的小日子～',
          ],
          friends_impression: [],
          questions_answers: [
            { A: '', Q: '' },
            { A: '', Q: '' },
            { A: '', Q: '' },
          ],
          age: 25,
          height: 170,
          city: '杭州市',
          university: '浙江传媒学院',
          ideal_object: {
            理想对象介绍: '希望你对感情专一 有稳定的工作和收入 对女朋友好 为人善良有责任心 生活健康 圈子干净',
          },
          ideal_object_tags: ['比较主动', '总是充满热情', '话痨'],
          remark: '',
          tags: [],
          common_tags: ['有房', '170cm', '模特', '艺术院校'],
          admin_set_tags: ['模特', '艺术院校'],
          platform: 'mini',
          is_on_wall: true,
          is_real_name_auth: false,
          is_show: true,
          is_ban: false,
          sort: 100,
          score: 2770,
          status: '审核通过',
          update_count: 28,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1704297600000,
          update_date: 1721959833531,
          is_buy: false,
          private_info: { 年收入: '10', 微信号: '申请通过后，可解锁', 是否购房: '是', 是否购车: '否' },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_3.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: 'a0935a51-5302-478c-83a5-c0d380a97b8a',
          uid: 'a999c406-de5d-4a79-8247-ad129e7059e0',
          customer_group: [],
          name: '宝乐儿',
          avatar: 'https://static.hamu.site/blind/11c942942507419b9aac907ea94ea4ee.png',
          is_only: [],
          only_content: '',
          operate_id: '100001',
          operate_type: '微信小程序',
          cover_img: 'https://static.hamu.site/blind/11c942942507419b9aac907ea94ea4ee.png',
          img_list: [],
          image_list: [],
          gender: '女',
          birthday: 1037318400000,
          living_place: ['内蒙古自治区', '呼和浩特市'],
          hometown: ['内蒙古自治区', '呼和浩特市'],
          register_residence: ['内蒙古自治区', '呼和浩特市'],
          education: '本科',
          school: '内蒙古鸿德文理学院',
          work_unit: '无',
          assets: '50万内',
          job: '',
          position: ['学生', '大学生'],
          introduce: [
            '乐观，积极向上\n有时会有点小脾气💙💚💛💜❤️\n希望对方是乐观向上有包容心并且可以带领我前进的男生\n👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌👌',
          ],
          friends_impression: [],
          questions_answers: [
            { A: '', Q: '' },
            { A: '', Q: '' },
            { A: '', Q: '' },
          ],
          age: 21,
          height: 170,
          city: '呼和浩特市',
          university: '内蒙古鸿德文理学院',
          ideal_object: { 理想对象介绍: '希望你可以比较耐心' },
          ideal_object_tags: [],
          remark: '',
          tags: [],
          common_tags: ['170cm'],
          admin_set_tags: [],
          sea_operator_id: '',
          sea_type: '',
          sea_status: '',
          sea_current_id: '',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 0,
          score: 1,
          status: '审核通过',
          update_count: 18,
          is_open_invite: false,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1656248915882,
          update_date: 1720160444916,
          is_buy: false,
          private_info: { 年收入: '0', 微信号: '申请通过后，可解锁', 是否购房: '否' },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: false,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_2.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '31048964-b549-4bee-b728-3272cb429e4d',
          uid: '0099a4d0-5e8b-4d1e-8736-000298ccd572',
          customer_group: [],
          vip_type: 'V1',
          name: '恬甜',
          avatar: 'https://static.hamu.site/blind/58622ca22ed949959738136b28ce1e97.png',
          is_only: [],
          only_content: '',
          operate_id: '246886',
          operate_type: '微信小程序-核心资料',
          cover_img: 'https://static.hamu.site/blind/58622ca22ed949959738136b28ce1e97.png',
          img_list: [],
          image_list: [
            { type: 'travel', image: '' },
            { type: 'favorite', image: '' },
            { type: 'more', image: '' },
          ],
          gender: '女',
          birthday: 982972800000,
          living_place: ['安徽省', '合肥市'],
          hometown: ['安徽省', '合肥市'],
          register_residence: ['安徽省', '合肥市'],
          education: '本科',
          school: '广州体育学院',
          work_unit: '无',
          assets: '50万内',
          job: '',
          position: ['学生', '大学生'],
          introduce: [
            '关于我：\n\n⭕️Hi！你好啊，我是恬甜🎀\n\n我是双鱼座♓️，带双鱼的特质\n\n但没有星座描述的那么严重\n\n\n🎈性格方面\n\n多数是活泼开朗\n\n但是偶尔脾气会有点点大\n\n说话会比较直接，不会藏着掖着\n\n但如果是微信聊天，一开始会觉得我比较高冷\n\n但相处久了之后，就会发现其实我很好相处\n\n偶尔也是一个想法经常变换的人✨\n\n然后性格有点矛盾纠结，会犯选择困难做\n\n平时会比较理性，尤其是对待感情方面\n\n也不会恋爱脑，希望彼此之间真诚第一☝️\n\n\n\n小姐姐有无有趣或者难忘的回忆：让我印象最深刻的一次旅行是去丽江的玉龙雪山🏔️，去的前一天说是天气不太好，本来还有点失落的💔，但是当天早上去的时候，天气却意外地好，我们去到了最高的4680米，看到的景色特别美！\n\n\n\n到现在回想起来都会被震撼，再加上那次遇见的民宿老板刚好是我的同乡，所以特别亲切，感觉整趟旅程都是美好和温馨的💗。\n\n兴趣爱好：\n\n我平常的兴趣爱好挺多的\n\n喜欢旅游🚗\n\n喜欢到处出去走走，看看祖国的景秀山河\n\n去过长沙、上海、南京、云南等等好多地方\n\n\n\n平时我也喜欢看电影看书🎬\n\n电影方面我比较喜欢爱情片\n\n像是《恋恋笔记本》、《重庆森林》\n\n《这个杀手不太冷》、《怦然心动》等等…\n\n我都很喜欢，谁能拒绝甜甜的恋爱呢💗～\n\n周末或者放假的时候☀️\n\n我也会和同学去探探店、拍拍照📷\n\n吃吃好吃的🍩，如果遇上了还不错的店\n\n我也会写一些攻略和小心得po在社交平台上',
          ],
          friends_impression: [
            '她是个很可爱、很有趣的女孩，喜欢拍照、喜欢探店，喜欢探索新鲜的事物。',
            '活泼开朗，很好相处的女生，跟她待在一起很舒服。',
          ],
          questions_answers: [],
          age: 23,
          height: 168,
          city: '合肥市',
          university: '广州体育学院',
          ideal_object: { 理想对象介绍: '真诚待人，互相尊重，有人格魅力\n' },
          ideal_object_tags: [],
          remark: '',
          tags: [
            '倾听者',
            '猎奇',
            '积极乐观',
            '有点小幽默',
            '看电影',
            '听音乐',
            '拍照片',
            '寻觅美食',
            '游乐场',
            '唱歌',
            '容易相处',
            '善于交际',
            '有氧运动',
            '旅游爱好者',
            '总是充满热情',
          ],
          common_tags: ['168cm'],
          admin_set_tags: [],
          sea_operator_id: '',
          sea_type: '',
          sea_status: '',
          sea_current_id: '',
          platform: 'mini',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 117,
          score: 1,
          status: '审核通过',
          update_count: 103,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1645632000000,
          update_date: 1723079801360,
          is_buy: false,
          private_info: {
            年收入: '0',
            微信号: '申请通过后，可解锁',
            家庭背景:
              '父母是做生意的，还有一个哥哥，家里人都很宠我，氛围很和睦，父母很开明，都很平易近人，很好沟通～\n\n',
            是否购房: '否',
            是否购车: '否',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_6.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '20495810-7e92-4010-a414-26594165e9a8',
          uid: '6ea7ec7c-2d1b-406a-9d19-4aca585e6e6c',
          customer_group: [],
          vip_type: 'V1',
          name: '刘璐',
          avatar: 'https://static.hamu.site/blind/60497463968e401695499160e52131d5/1663647306790.png',
          is_only: [],
          only_content: '',
          operate_id: '100000',
          operate_type: '微信小程序-社群',
          cover_img: 'https://static.hamu.site/blind/60497463968e401695499160e52131d5/1663647306790.png',
          img_list: [
            'https://static.hamu.site/blind/284de756cae74c78a140709db681b263.png',
            'https://static.hamu.site/blind/6b0d4c0891e141b0b54548b66d1159ab.png',
            'https://static.hamu.site/blind/19389d22c1744d35991a243b317e1bb1.png',
          ],
          image_list: [
            { type: 'travel', image: 'https://static.hamu.site/blind/284de756cae74c78a140709db681b263.png' },
            { type: 'favorite', image: 'https://static.hamu.site/blind/6b0d4c0891e141b0b54548b66d1159ab.png' },
            { type: 'more', image: 'https://static.hamu.site/blind/19389d22c1744d35991a243b317e1bb1.png' },
          ],
          gender: '女',
          birthday: 765158400000,
          living_place: ['上海市'],
          hometown: ['山东省', '济南市'],
          register_residence: ['山东省', '济南市'],
          education: '硕士',
          school: '英国巴斯斯巴大学',
          work_unit: '双语学校',
          assets: '50万内',
          job: '',
          position: ['老师', '初中老师'],
          introduce: [
            '关于我：\n嗨～你好呀，我是璐璐，\n🐣出生在山东济南，\n👩🏻‍🎓硕士毕业于英国巴斯斯巴大学，\n📌现在定居上海，在上海做舞蹈老师；\n\n♈简单 直接\n我是一个典型的白羊座。性格直爽脾气超好，我所热爱追求的是健康和快乐，一路走走停停，拾得人间风景柔情。携手三餐四季、山温水暖、你我安然，这便是天大的福分。\n\n兴趣爱好：\n✈️最喜欢旅行，我觉得生活最理想的状态是一半是柴米油盐，一半是山川湖海',
          ],
          friends_impression: [
            '她是个超级佛系的女孩，温柔且上进，内心坚定有力量，心情不好的时候跟她聊会天就会舒畅很多，她是那种可以在不知不觉中把稳定的情绪传递给你的人，跟她待在一起超级知足！',
            '这是什么仙女小姐姐，长发飘飘，舞姿绝美，对朋友慷慨大方，也爱笑爱闹，所有的烦恼在她面前都可以解决，这样的乐天派，和她在一起，总能保持愉快的心情！',
          ],
          questions_answers: [],
          age: 30,
          height: 162,
          city: '上海市',
          university: '英国巴斯斯巴大学',
          ideal_object: {
            理想对象介绍:
              '1. 希望你坐标上海，身高175cm以上，\n\n2. 希望你心智成熟，对事物有自己独到的看法；\n\n3. 希望你性格幽默，可以为我们的生活增添乐趣；\n\n4. 希望你为人低调高情商，安安稳稳的经营我们的生活！\n\n5.如果是医生或律师会有加分哦~\n',
          },
          ideal_object_tags: [
            '旅游爱好者',
            '比较主动',
            '有始有终',
            '篮球',
            '冲浪',
            '滑雪',
            '潜水',
            '爱车一族',
            '养宠物',
            '做饭',
            '游乐场',
            '逛博物馆',
            '寻觅美食',
            '蹦迪',
            '密室逃脱',
            '看电影',
            '看书',
            '蹦极',
            '极限运动',
          ],
          remark: '',
          tags: [
            '喜欢安静',
            '喜爱冒险',
            '拍照片',
            '养宠物',
            '游乐场',
            '跳舞',
            '潜水',
            '漂流',
            '容易相处',
            '猎奇',
            '寻觅美食',
            '旅游爱好者',
            '极限运动',
            '冲浪',
            '滑雪',
            '蹦极',
            '慢走',
            '游泳',
            '羽毛球',
          ],
          common_tags: ['硕士', '老师'],
          admin_set_tags: [],
          sea_operator_id: '357950',
          sea_type: '社群',
          sea_status: 'C',
          sea_current_id: '01d72a72-24cc-4c08-90e1-805a1c8b0839',
          platform: 'mini',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 99,
          score: 1,
          status: '审核通过',
          update_count: 17,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1645545600000,
          update_date: 1720444372458,
          is_buy: false,
          private_info: {
            年收入: '15',
            微信号: '申请通过后，可解锁',
            家庭背景:
              '我家麻雀虽小，五脏俱全，父母从小尊重我自己的意见，给了我足够的爱，一直很支持我追求我自己的梦想。',
            是否购房: '否',
            是否购车: '否',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_4.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: '1dc19496-9435-4199-b8d8-b58c75721885',
          uid: 'a4b77259-07d8-48a1-9ae9-b054754bb7c4',
          customer_group: [],
          vip_type: 'V0',
          name: '马铭蔚',
          avatar: 'https://static.hamu.site/blind/5067484340374414821b102be7e61122/1665199447394.png',
          is_only: ['是'],
          only_content: '',
          operate_id: '4547cbc1-6448-44ae-8d7e-c335b6dc45c4',
          operate_type: '买微信',
          cover_img: 'https://static.hamu.site/blind/5067484340374414821b102be7e61122/1665199447394.png',
          img_list: [
            'https://static.hamu.site/blind/6e29303ec2764685aeae9e475484d529/1665199459889.png',
            'https://static.hamu.site/blind/266e459cd0214a9bab079cb45946379d/1665199472669.png',
            'https://static.hamu.site/blind/51d320445ede402d9dd1cc14a6a24014/1665199542936.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 671472000000,
          living_place: ['广东省', '深圳市'],
          hometown: ['广东省', '汕头市'],
          register_residence: ['广东省', '汕头市'],
          education: '本科',
          school: '北京师范大学珠海分校',
          job: '银行',
          position: ['金融', '互联网金融'],
          introduce: [
            '关于我：\n\nhi～你好呀🙋\n\n很高兴认识你\n\n♈️一个安静的白羊座\n\n📌 出生于广东省汕头市\n\n💻目前在深圳某银行工作\n\n\n\n经济比较独立，有储蓄和理财意识\n\n物欲不强，不爱买名牌鞋包\n\n日常穿衣打扮以舒适简洁和适合自己为主\n\n\n\n我平时的的性格比较安静内向\n\n虽然我是白羊座，但跟白羊风风火火\n\n外向热情的特点不一样🤔\n\n比起一群人热热闹闹，各种交际\n\n我更加喜欢一个人在安静地做自己的事\n\n兴趣爱好：\n\n比较宅，不爱到处乱跑\n\n比起环游世界，更爱在家待着\n\n看书📖，学习中国传统文化\n\n烹饪、烘焙🥯或者是陪陪家人\n\n出门基本是工作和闺蜜小聚\n\n\n\n务实派，不贪玩，不爱出门聚会蹦迪\n\n不抽烟喝酒，没有纹身，不整容\n\n也没有什么特别放飞狂野的兴趣爱好\n\n平时就单位-家两点一线',
          ],
          friends_impression: ['有点傻白甜哈哈哈，平时有点憨憨的，没什么心机，很可爱的女孩。'],
          questions_answers: [{ A: '', Q: '' }],
          age: 31,
          height: 168,
          city: '深圳市',
          university: '北京师范大学珠海分校',
          ideal_object: {
            理想对象介绍:
              '坐标要求:   广东省-深圳市\n外貌要求:   五官端正，身体健康，身高168cm以上\n学历要求:   专科\n年龄范围:   28-45岁\n收入要求:   25万\n身高要求:   170cm\n其他要求:   希望你性格比较外向，是个开朗阳光的人。\n',
          },
          ideal_object_tags: ['有点小幽默', '足球'],
          remark: '',
          tags: [],
          common_tags: ['年入30万', '168cm'],
          admin_set_tags: [],
          sea_operator_id: '271545',
          sea_type:
            '前一天喜欢嘉宾:http://mp-admin.smcode.com.cn/operator/user_detail?id=68d55809-7008-4423-ae84-cd60b2137388&name=Brian&type=0&source=all',
          sea_status: 'E',
          sea_current_id: '5b07970e-1d3b-437d-9275-490250c0db8b',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 86,
          score: 1,
          status: '审核通过',
          update_count: 2,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: -28800000,
          update_date: 1721650701789,
          is_buy: false,
          private_info: {
            年收入: 30,
            微信号: '申请通过后，可解锁',
            家庭背景:
              '潮汕人，所以家中还有一妹一弟，弟弟性格独立有担会付出，不需要我扶弟。父亲是做生意，母亲是家庭主妇，家庭氛围和睦。\n\n',
            是否购房: '否',
          },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_9.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
        {
          id: 'bc1a1c94-68d7-488e-9a4a-3c211554c1b2',
          uid: '2c6476c8-2077-49a5-a0b8-0b1e2e86ec40',
          customer_group: [],
          name: '刘牛牛',
          avatar: 'https://static.hamu.site/blind/2ea94997b927440182b9d08ac05ac347/1683881037169.png',
          is_only: [],
          only_content: '',
          operate_id: '100000',
          operate_type: '微信小程序-核心资料',
          cover_img: 'https://static.hamu.site/blind/2ea94997b927440182b9d08ac05ac347/1683881037169.png',
          img_list: [
            'https://static.hamu.site/blind/078997919cec4562be4082b58d96c4d6/1683786588480.png',
            'https://static.hamu.site/blind/2a14087b12454d9189d7de899d497b95/1683881124972.png',
          ],
          image_list: [],
          gender: '女',
          birthday: 815788800000,
          living_place: ['北京市'],
          hometown: ['广东省', '珠海市'],
          register_residence: ['广东省', '珠海市'],
          education: '硕士',
          school: '首尔大学',
          job: '',
          position: ['运营', '运营'],
          introduce: [
            '嗨~我是牛牛，具有坚决性和计划性，务实的浪漫主义ENTJ 。性格比较开朗、明媚、无论处境，永葆热情。较好的包容性和接纳性，我觉得我自己是一个富有同理心的人。\n\n18岁之前，成长轨迹在很南的南方，18-25岁这几年的价值观养成在国外，北京是目前人生中最重要阶段的第五座城市，想爱上它。\n\n留过学，开过店，创过业，目前在互联网做策略运营，【喜欢温柔、真诚且深刻的人】\n\n兴趣爱好：平时比较自律，喜欢运动，跑过马拉松，一周最少三次10km，三次健身房力量训练。\n\n喜欢看展，美食探店分享，看杂七杂八的书，看电影（豆瓣观影记录800➕），超级音乐迷！唱歌也还可以～\n\n家庭氛围：独生，家庭氛围温和有爱。',
          ],
          friends_impression: [
            '牛牛是我朋友当中最阳光的一个人了，真的好明媚啊！而且特别热爱运动，经常还会拉着我去跑步～',
            '我太喜欢真诚的人了，我最怕人不real，牛牛不仅真诚，还是坦率的真诚，能处！！',
          ],
          questions_answers: [],
          age: 27,
          height: 171,
          city: '北京市',
          university: '首尔大学',
          ideal_object: {
            理想对象介绍:
              '坐标要求:   北京市\n学历要求:   本科\n年龄范围:   25-38岁\n是否有房:   是\n收入要求:   60万\n身高要求:   176cm\n其他要求:   希望你情绪稳定，性格开朗温和。\n',
          },
          ideal_object_tags: [],
          remark: '',
          tags: ['非常自律', '积极乐观', '有始有终', '善于交际', '总是充满热情', '倾听者', '容易相处'],
          common_tags: ['有房', '年入60万', '171cm', '硕士', 'QS29', '大厂'],
          admin_set_tags: ['QS29', '大厂'],
          sea_operator_id: '458476',
          sea_type:
            '前一天喜欢嘉宾:http://mp-admin.smcode.com.cn/operator/user_detail?id=85e0ecb5-670c-424b-8e57-801a064c5058&name=黄志鹏&type=0&source=all',
          sea_status: 'C',
          sea_current_id: '41d65341-20a4-4b2d-ac5a-5ad388e898e9',
          is_on_wall: true,
          is_real_name_auth: true,
          is_show: true,
          is_ban: false,
          sort: 85,
          score: 1,
          status: '审核通过',
          update_count: 4,
          is_open_invite: true,
          is_removed: false,
          insert_wechat_date: 0,
          is_update_privacy: true,
          create_date: 1628438400000,
          update_date: 1720496590804,
          is_buy: false,
          private_info: { 年收入: '60', 微信号: '申请通过后，可解锁', 是否购房: '是' },
          applyRecord: { is_apply: false, status: '未申请' },
          is_follow: false,
          is_send_flower: true,
          is_follower: false,
          price: 49,
          isBindUser: true,
          is_exposure: false,
          exchange: 49,
          background: 'https://static.hamu.site/2021_10_11/recommend_9.png?imageView2/1/w/348/h/135/format/webp/q/80',
        },
      ]);
      this.recommends.value = recommends;
    },
  },
});

export const useSevenDaysStore = defineStore('sevenDays', {
  state: () => ({
    list: ref([]),
  }),
  actions: {
    getSevenDays() {
      const list = ref([
        {
          id: 'a5c00382-ec82-4b02-a69a-00ad2c832b80',
          uid: '89328008-5c87-4708-82b8-8d52e2be033d',
          height: 160,
          position: ['工程师'],
          name: 'kimi',
          birthday: 1004124085860,
          avatar: 'https://cdn.nodejs.cloud//blind/18966556be6b4d899e689427d4c03503.png',
          gender: '女',
          city: '深圳市',
          living_place: ['广东省', '深圳市'],
          university: '本科',
          job: '',
          education: '本科',
          score: 29,
          age: 23,
        },
        {
          id: '6a0c12b6-2e92-48b6-8832-49344a281e62',
          uid: '98040b88-26b7-4e18-98d8-68a590c585e8',
          height: 161,
          position: ['学生'],
          name: '随便吧阿巴',
          birthday: 1067155711713,
          avatar: 'https://cdn.nodejs.cloud//blind/6d24001e942641949e34a719591d1623.png',
          gender: '女',
          city: '广州市',
          living_place: ['广东省', '广州市'],
          university: '本科',
          job: '',
          education: '本科',
          score: 26,
          age: 21,
        },
        {
          id: '4b006366-0423-499e-a98b-2007d7400083',
          uid: '15987d0c-b235-4182-8da1-50e8ae1758a8',
          height: 160,
          position: ['合成研究员'],
          name: '索菲亚',
          birthday: 972573408974,
          avatar: 'https://cdn.nodejs.cloud//blind/94808432ad644a3b954c44853ab438e2.png',
          gender: '女',
          city: '北京市',
          living_place: ['北京市'],
          university: '本科',
          job: '',
          education: '本科',
          score: 19,
          age: 24,
        },
        {
          id: '48596b76-d422-4c8a-b072-c1be06d0b0d2',
          uid: 'c05b39c7-1452-4b3c-a74c-7b28d4454816',
          height: 170,
          position: ['写手，占卜师'],
          name: 'Future',
          birthday: 887587200000,
          avatar: 'https://cdn.nodejs.cloud//blind/767e26b2e69441a083c8a7210034d60d.png',
          gender: '女',
          city: '北京市',
          living_place: ['北京市'],
          university: '本科',
          job: '',
          education: '本科',
          score: 18,
          age: 26,
        },
        {
          id: '2767293a-04c9-494d-8999-77b710d01e1b',
          uid: 'd430d588-11cb-43d3-887a-eea7c4b444e8',
          height: 162,
          position: [],
          name: '深圳刘亦菲',
          birthday: 814775329062,
          avatar: 'https://cdn.nodejs.cloud//blind/3cd7c86556a34033b6940043512648ca.png',
          gender: '女',
          city: '深圳市',
          living_place: ['广东省', '深圳市'],
          university: '本科',
          job: '',
          education: '本科',
          score: 11,
          age: 29,
        },
        {
          id: '1a8e7198-a410-46c8-a381-452041a0519a',
          uid: '075185ad-b39c-4437-bb78-4874ecdc3cd7',
          height: 167,
          position: ['餐饮副店长'],
          name: '闺女是我的宝',
          birthday: 972835831356,
          avatar: 'https://cdn.nodejs.cloud//blind/26120c40c62244a8adc8a6ece1b947a5.png',
          gender: '女',
          city: '北京市',
          living_place: ['北京市'],
          university: '专科',
          job: '',
          education: '专科',
          score: 10,
          age: 24,
        },
      ]);
      this.list.value = list.value;
    },
  },
});
